# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='activity',
            field=models.ManyToManyField(to='Requests.Activity'),
        ),
    ]
