# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_ngoprofile_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=b''),
        ),
    ]
