# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20160415_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
