# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_ngoemployeeprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGODomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_id', models.TextField(blank=True, max_length=100)),
                ('Domain', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='ngo_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
