# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20160613_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngodomains',
            name='ngo_id',
        ),
    ]
