# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_ngoprofile_ngo_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngodomains',
            old_name='Domain',
            new_name='domain',
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='ngo_domain',
            field=models.IntegerField(blank=True),
        ),
    ]
