# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_auto_20160614_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoprofile',
            name='ngo_domain',
            field=models.IntegerField(blank=True, max_length=4),
        ),
    ]
