# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='projects',
            name='activity_goal',
            field=models.TextField(default=b'', max_length=240),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='volunteer_ngo_request',
            name='req_type',
            field=models.TextField(default=b'NGO'),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='activities',
        ),
        migrations.AddField(
            model_name='projects',
            name='activities',
            field=models.ManyToManyField(to='Requests.Activity'),
        ),
    ]
