# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0006_remove_volunteer_ngo_request_date_time_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_ngo_request',
            name='date_time_req',
            field=models.DateTimeField(auto_now_add=True, default='null'),
            preserve_default=False,
        ),
    ]
