# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0008_remove_volunteer_ngo_request_date_time_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_ngo_request',
            name='date_time_req',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 26, 5, 58, 0, 855000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
