# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0010_remove_volunteer_ngo_request_date_time_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_ngo_request',
            name='accept',
            field=models.TextField(default=b'Reject'),
        ),
    ]
