# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0011_volunteer_ngo_request_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_ngo_request',
            name='date_time_req',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 26, 13, 2, 5, 487000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
