# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0018_auto_20160614_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_ngo_request',
            name='time_vol',
            field=models.TimeField(default=datetime.datetime(2016, 6, 14, 16, 28, 32, 298000)),
        ),
    ]
