# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0039_auto_20160616_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_ngo_request',
            name='date_vol',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer_ngo_request',
            name='time_vol',
            field=models.TimeField(blank=True),
        ),
    ]
