# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0040_auto_20160616_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='feedback_ngo',
        ),
        migrations.RemoveField(
            model_name='events',
            name='feedback_ngorating',
        ),
        migrations.RemoveField(
            model_name='events',
            name='feedback_user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='feedback_userrating',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='feedback_ngo',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='feedback_ngorating',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='feedback_user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='feedback_userrating',
        ),
    ]
